// Generated by CoffeeScript 1.10.0
(function() {
  var JSONStream, argv, bucket, cluster, couchbase, es, fs, processLocation;

  fs = require('fs');

  JSONStream = require('JSONStream');

  es = require('event-stream');

  argv = require('yargs').demand('f').alias('f', 'file').check(function(argv, options) {
    var e, error;
    try {
      fs.accessSync(argv.f, fs.F_OK);
      return true;
    } catch (error) {
      e = error;
      return false;
    }
  }).nargs('f', 1).help('h').alias('h', 'help').argv;

  console.log(argv.f);

  processLocation = function(location, verbose, bucket) {
    return bucket.upsert('pedro-gl-' + location.timestampMs, location, function(err, result) {
      if (err) {
        throw err;
      }
      if (verbose) {
        return console.log(result.value);
      }
    });
  };

  couchbase = require('couchbase');

  cluster = new couchbase.Cluster('couchbase://192.168.33.10');

  bucket = cluster.openBucket('glocations');

  fs.access(argv.f, fs.F_OK, function(err) {
    var fileStream;
    if (!err) {
      fileStream = fs.createReadStream(argv.f, {
        encoding: 'utf8'
      });
      return fileStream.pipe(JSONStream.parse('locations.*')).pipe(es.through(function(data) {
        console.log('location of file::');
        console.log(data);
        return processLocation(data, false, bucket);
      }, function() {
        console.log('stream reading ended');
        return this.emit('end');
      }));
    }
  });

}).call(this);
